In [2]:
pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 55.4 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [6]:
list = [ 2,34,56,44]
arr = np.array(list)
arr

array([ 2, 34, 56, 44])

In [7]:
arr.shape

(4,)

In [9]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
list3 = [7, 8, 9]

arr = np.array([list1, list2, list3])
arr



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr.shape

(3, 3)

In [18]:
 arr.reshape(1,9)
 arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

INDEXING

In [22]:
arr = np.array([1,2,3])
print(arr[0])

1


In [28]:
list1 = [1, 2, 3, 5]
list2 = [4, 5, 6, 7]
list3 = [7, 8, 9, 8]

arr = np.array([list1, list2, list3])

arr

array([[1, 2, 3, 5],
       [4, 5, 6, 7],
       [7, 8, 9, 8]])

In [33]:
arr[0:2,:]

array([[1, 2, 3, 5],
       [4, 5, 6, 7]])

In [34]:
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [36]:
arr[1:,2:]

array([[6, 7],
       [9, 8]])

In [37]:
arr[1:,1:3]

array([[5, 6],
       [8, 9]])

In [38]:
arr[1:2,1:3]

array([[5, 6]])